export const COM_STATUS = 'COM_STATUS'
// HEADER
export const HEADER_SET_SHOWBACK = 'HEADER_SET_SHOWBACK'
export const HEADER_SET_SHOWCENTER = 'HEADER_SET_SHOWCENTER'
// BOTTOM
export const BOTTOM_SHOW_BOTTOM = 'BOTTOM_SHOW_BOTTOM'
export const BOTTOM_SET_BOTTOM_TYPE = 'BOTTOM_SET_BOTTOM_TYPE'
// HOME
export const HOME_SET_BANNERS = 'HOME_SET_BANNERS'
export const HOME_SET_CATEGORY = 'HOME_SET_CATEGORY'
export const HOME_ADD_CATEGORY_PAGE = 'HOME_ADD_CATEGORY_PAGE'
export const HOME_ADD_FOODS_PAGE = 'HOME_ADD_FOODS_PAGE'
export const HOME_SET_FOODS = 'HOME_SET_FOODS'
export const HOME_INIT_FOODS_PAGE = 'HOME_INIT_FOODS_PAGE'

// bottom
export const BOTTOM_ADD_FOODS_BASKET = 'BOTTOM_ADD_FOODS_BASKET'
export const BOTTOM_CLEAR_FOODS_BASKET = 'BOTTOM_CLEAR_FOODS_BASKET'
export const BOTTOM_CHANGE_FOODS_BASKET = 'BOTTOM_CHANGE_FOODS_BASKET'
export const BOTTOM_CHANGE_DELETE_BASKET = 'BOTTOM_CHANGE_DELETE_BASKET'
export const BOTTOM_UPDATE_FOODS_BASKET = 'BOTTOM_UPDATE_FOODS_BASKET'
