export const COM_STATUS = 'COM_STATUS'

// HOME
export const HOME_SET_BANNERS = 'HOME_SET_BANNERS'
export const HOME_SET_CATEGORY = 'HOME_SET_CATEGORY'
export const HOME_ADD_CATEGORY_PAGE = 'HOME_ADD_CATEGORY_PAGE'
export const HOME_ADD_FOODS_PAGE = 'HOME_ADD_FOODS_PAGE'
export const HOME_SET_FOODS = 'HOME_SET_FOODS'
export const HOME_INIT_FOODS_PAGE = 'HOME_INIT_FOODS_PAGE'

// bottom
export const BOTTOM_ADD_FOODS_BASKET = 'BOTTOM_ADD_FOODS_BASKET'
export const BOTTOM_CLEAR_FOODS_BASKET = 'BOTTOM_CLEAR_FOODS_BASKET'
